/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icons: typeof import('./src/components/base/Icons.vue')['default']
    ListPopup: typeof import('./src/components/tools/ListPopup.vue')['default']
    LoadIcon: typeof import('./src/components/base/LoadIcon.vue')['default']
    Loading: typeof import('./src/components/tools/Loading.vue')['default']
    MusicList: typeof import('./src/components/page/MusicList.vue')['default']
    Nav: typeof import('./src/components/page/Nav.vue')['default']
    NoData: typeof import('./src/components/tools/NoData.vue')['default']
    Pagination: typeof import('./src/components/tools/Pagination.vue')['default']
    PlayMod: typeof import('./src/components/page/PlayMod.vue')['default']
    Popup: typeof import('./src/components/base/Popup.vue')['default']
    PositionPopup: typeof import('./src/components/tools/PositionPopup.vue')['default']
    Progress: typeof import('./src/components/base/Progress.vue')['default']
    RightBtns: typeof import('./src/components/page/RightBtns.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongListItem: typeof import('./src/components/base/SongListItem.vue')['default']
    Tabs: typeof import('./src/components/page/Tabs.vue')['default']
    YScroll: typeof import('./src/components/tools/y-scroll.vue')['default']
  }
}
