/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icons: typeof import('./src/components/base/Icons.vue')['default']
    LayoutBottom: typeof import('./src/components/page/LayoutBottom.vue')['default']
    LayoutLeft: typeof import('./src/components/base/LayoutLeft.vue')['default']
    ListAddModal: typeof import('./src/components/operate/ListAddModal.vue')['default']
    ListPopup: typeof import('./src/components/tools/ListPopup.vue')['default']
    LoadIcon: typeof import('./src/components/base/LoadIcon.vue')['default']
    Loading: typeof import('./src/components/tools/Loading.vue')['default']
    LyricPage: typeof import('./src/components/page/LyricPage.vue')['default']
    MusicList: typeof import('./src/components/page/MusicList.vue')['default']
    Nav: typeof import('./src/components/page/Nav.vue')['default']
    NoData: typeof import('./src/components/tools/NoData.vue')['default']
    OperateModal: typeof import('./src/components/tools/OperateModal.vue')['default']
    Pagination: typeof import('./src/components/tools/Pagination.vue')['default']
    PlayMod: typeof import('./src/components/page/PlayMod.vue')['default']
    PlayStateMod: typeof import('./src/components/page/PlayStateMod.vue')['default']
    Popup: typeof import('./src/components/base/Popup.vue')['default']
    PositionPopup: typeof import('./src/components/tools/PositionPopup.vue')['default']
    Progress: typeof import('./src/components/base/Progress.vue')['default']
    RightBtns: typeof import('./src/components/page/RightBtns.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/base/SearchInput.vue')['default']
    SetTitle: typeof import('./src/components/base/SetTitle.vue')['default']
    SongListItem: typeof import('./src/components/base/SongListItem.vue')['default']
    Tabs: typeof import('./src/components/page/Tabs.vue')['default']
    TipPopup: typeof import('./src/components/tools/TipPopup.vue')['default']
    Tiptool: typeof import('./src/components/tools/Tiptool.vue')['default']
    TransitionOpacity: typeof import('./src/components/transition/TransitionOpacity.vue')['default']
    TransitionPosition: typeof import('./src/components/transition/TransitionPosition.vue')['default']
    TransitionScale: typeof import('./src/components/transition/TransitionScale.vue')['default']
    YScroll: typeof import('./src/components/tools/y-scroll.vue')['default']
  }
}
